fullname: i27-eureka
replicas:
  default: 1
image:
  name: devopsb5.jfrog.io/cart-docker/eureka
  tag: random
targetPort: 8761 # this will be overridden by the values.yaml file in the aplication environment folder