name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  Checkout:
    runs-on: ubuntu-latest
    outputs:
      commit_sha: ${{ steps.get_sha.outputs.commit_sha }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Get Commit SHA
        id: get_sha
        run: |
          echo "commit_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

  Build:
    needs: Checkout
    runs-on: ubuntu-latest
    strategy:
      matrix:
        language:
          - java
          - node
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Setup Java
      - name: Setup Java
        if: matrix.language == 'java'
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Setup Node
      - name: Setup Node.js
        if: matrix.language == 'node'
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2
            ~/.npm
          key: ${{ runner.os }}-${{ matrix.language }}-${{ hashFiles('**/pom.xml', '**/package-lock.json') }}

      # Java build
      - name: Build Java App
        if: matrix.language == 'java'
        run: mvn clean package -DskipTests

      # Node build
      - name: Build Node App
        if: matrix.language == 'node'
        run: |
          cd frontend
          npm install
          npm run build
